/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    solicitudes: Solicitude;
    'modelos-repuesto': ModelosRepuesto;
    marcas: Marca;
    'tipos-equipo': TiposEquipo;
    'categorias-tecnicas': CategoriasTecnica;
    'equipos-nuevos': EquiposNuevo;
    'equipos-usados': EquiposUsado;
    'marcas-maquinaria': MarcasMaquinaria;
    'tipos-maquinaria': TiposMaquinaria;
    'categorias-maquinaria': CategoriasMaquinaria;
    'categorias-usada': CategoriasUsada;
    'marcas-lubricante': MarcasLubricante;
    'categorias-lubricante': CategoriasLubricante;
    paginas: Pagina;
    articulos: Articulo;
    'categorias-blog': CategoriasBlog;
    'preguntas-frecuentes': PreguntasFrecuente;
    testimonios: Testimonio;
    sedes: Sede;
    media: Media;
    documentos: Documento;
    videos: Video;
    animaciones: Animacion;
    redirects: Redirect;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    solicitudes: SolicitudesSelect<false> | SolicitudesSelect<true>;
    'modelos-repuesto': ModelosRepuestoSelect<false> | ModelosRepuestoSelect<true>;
    marcas: MarcasSelect<false> | MarcasSelect<true>;
    'tipos-equipo': TiposEquipoSelect<false> | TiposEquipoSelect<true>;
    'categorias-tecnicas': CategoriasTecnicasSelect<false> | CategoriasTecnicasSelect<true>;
    'equipos-nuevos': EquiposNuevosSelect<false> | EquiposNuevosSelect<true>;
    'equipos-usados': EquiposUsadosSelect<false> | EquiposUsadosSelect<true>;
    'marcas-maquinaria': MarcasMaquinariaSelect<false> | MarcasMaquinariaSelect<true>;
    'tipos-maquinaria': TiposMaquinariaSelect<false> | TiposMaquinariaSelect<true>;
    'categorias-maquinaria': CategoriasMaquinariaSelect<false> | CategoriasMaquinariaSelect<true>;
    'categorias-usada': CategoriasUsadaSelect<false> | CategoriasUsadaSelect<true>;
    'marcas-lubricante': MarcasLubricanteSelect<false> | MarcasLubricanteSelect<true>;
    'categorias-lubricante': CategoriasLubricanteSelect<false> | CategoriasLubricanteSelect<true>;
    paginas: PaginasSelect<false> | PaginasSelect<true>;
    articulos: ArticulosSelect<false> | ArticulosSelect<true>;
    'categorias-blog': CategoriasBlogSelect<false> | CategoriasBlogSelect<true>;
    'preguntas-frecuentes': PreguntasFrecuentesSelect<false> | PreguntasFrecuentesSelect<true>;
    testimonios: TestimoniosSelect<false> | TestimoniosSelect<true>;
    sedes: SedesSelect<false> | SedesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documentos: DocumentosSelect<false> | DocumentosSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    animaciones: AnimacionesSelect<false> | AnimacionesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    cabecera: Cabecera;
    pie: Pie;
    seo: Seo;
    'ficha-producto': FichaProducto;
  };
  globalsSelect: {
    cabecera: CabeceraSelect<false> | CabeceraSelect<true>;
    pie: PieSelect<false> | PieSelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
    'ficha-producto': FichaProductoSelect<false> | FichaProductoSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Formularios enviados desde el sitio. Contienen datos personales: no se publican y solo son visibles aquí.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solicitudes".
 */
export interface Solicitude {
  id: number;
  tipo: 'contacto' | 'cotizacion' | 'repuesto';
  /**
   * Marcar como atendida en vez de borrar: conserva el historial.
   */
  estado: 'nueva' | 'atendida';
  nombre: string;
  correo: string;
  telefono?: string | null;
  empresa?: string | null;
  mensaje: string;
  /**
   * Se rellena solo cuando la solicitud sale de una ficha.
   */
  referencia?:
    | ({
        relationTo: 'equipos-nuevos';
        value: number | EquiposNuevo;
      } | null)
    | ({
        relationTo: 'modelos-repuesto';
        value: number | ModelosRepuesto;
      } | null);
  referenciaTexto?: string | null;
  /**
   * Página desde la que se envió el formulario.
   */
  origen?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipos-nuevos".
 */
export interface EquiposNuevo {
  id: number;
  nombre: string;
  /**
   * Es la última parte de la dirección web de esta página. Se crea sola a partir del nombre. Después ya no se puede cambiar, porque Google ya conoce esa dirección. Si tiene una errata, pide a un administrador el permiso «Puede editar slugs ya publicados»: la dirección antigua seguirá llevando a la nueva.
   */
  slug: string;
  /**
   * Tiene que ser la marca del tipo de equipo de abajo. Si la cambias, vuelve a elegir el tipo.
   */
  marca: number | MarcasMaquinaria;
  /**
   * Solo aparecen los tipos de la marca elegida arriba.
   */
  tipo: number | TiposMaquinaria;
  /**
   * Referencia del fabricante, ej. 1150M o ZX350LC-6.
   */
  codigo?: string | null;
  /**
   * Resumen de una o dos líneas, bajo el título.
   */
  entradilla?: string | null;
  descripcion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Ventajas o argumentos de venta, uno por línea.
   */
  destacados?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  /**
   * La primera imagen se usa como portada y como imagen social.
   */
  imagenes?: (number | Media)[] | null;
  /**
   * Pares etiqueta/valor tal como los publica el fabricante. No inventar datos: si no hay dato oficial, se deja fuera. Marca «Destacar» en hasta 4 filas: salen con su icono junto al título de la ficha (y las 3 primeras, en las tarjetas de otras referencias).
   */
  fichaTecnica?:
    | {
        /**
         * Ej. «Peso operativo», «Potencia neta».
         */
        etiqueta: string;
        /**
         * Incluir la unidad: «20.500 kg», «122 kW».
         */
        valor: string;
        /**
         * Junto al título de la ficha, con icono. Máximo 4.
         */
        destacar?: boolean | null;
        /**
         * Sin elegir, se usa «Otro dato».
         */
        icono?: ('peso' | 'potencia' | 'motor' | 'capacidad' | 'alcance' | 'profundidad' | 'velocidad' | 'otro') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Sale como «Descargar ficha técnica completa». Sin documento, el botón no aparece. Súbelo aquí con «Crear» (PDF, máximo 25 MB) o elige uno ya subido en «Documentos».
   */
  fichaTecnicaPdf?: (number | null) | Documento;
  /**
   * Imágenes de fichas o folletos del fabricante (JPEG, PNG o WebP). No se muestran en el sitio. El PDF de la ficha técnica va en «Ficha técnica completa (PDF)».
   */
  documentos?: (number | Media)[] | null;
  /**
   * Opcional. Debajo ves cómo saldrá en Google y qué se usa si lo dejas vacío.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marcas-maquinaria".
 */
export interface MarcasMaquinaria {
  id: number;
  nombre: string;
  /**
   * Es la última parte de la dirección web de esta página. Se crea sola a partir del nombre. Después ya no se puede cambiar, porque Google ya conoce esa dirección. Si tiene una errata, pide a un administrador el permiso «Puede editar slugs ya publicados»: la dirección antigua seguirá llevando a la nueva.
   */
  slug: string;
  descripcion?: string | null;
  logo?: (number | null) | Media;
  /**
   * Fondo de la tarjeta de esta marca en el inicio.
   */
  imagenTarjeta?: (number | null) | Media;
  /**
   * Vacío: no sale en la portada. 1, 2, 3… es el orden de las tarjetas de «Maquinaria pesada nueva» (en ux-9: Hitachi, CASE y Yanmar). Necesita la foto de la tarjeta.
   */
  ordenPortada?: number | null;
  /**
   * Opcional. Debajo ves cómo saldrá en Google y qué se usa si lo dejas vacío.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Fotos y logos del sitio, en JPEG, PNG o WebP, de hasta 15 MB (suben directo al almacén). El texto alternativo describe la imagen a quien no la ve.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe lo que se ve, como se lo contarías a alguien por teléfono: «Excavadora Hitachi ZX200 trabajando en una obra». Ni «foto1», ni «imagen», ni el nombre del fichero.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipos-maquinaria".
 */
export interface TiposMaquinaria {
  id: number;
  nombre: string;
  /**
   * Es la última parte de la dirección web de esta página. Se crea sola a partir del nombre. Después ya no se puede cambiar, porque Google ya conoce esa dirección. Si tiene una errata, pide a un administrador el permiso «Puede editar slugs ya publicados»: la dirección antigua seguirá llevando a la nueva.
   */
  slug: string;
  marca: number | MarcasMaquinaria;
  descripcion?: string | null;
  /**
   * Opcional. Debajo ves cómo saldrá en Google y qué se usa si lo dejas vacío.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Documentos en PDF para descargar desde el sitio (por ejemplo, la ficha técnica de un equipo). Máximo 25 MB. Las imágenes van en «Imágenes».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos".
 */
export interface Documento {
  id: number;
  /**
   * Para el panel. Ej. «Ficha técnica Hitachi ZX130-7H».
   */
  titulo: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modelos-repuesto".
 */
export interface ModelosRepuesto {
  id: number;
  nombre: string;
  /**
   * Es la última parte de la dirección web de esta página. Se crea sola a partir del nombre. Después ya no se puede cambiar, porque Google ya conoce esa dirección. Si tiene una errata, pide a un administrador el permiso «Puede editar slugs ya publicados»: la dirección antigua seguirá llevando a la nueva.
   */
  slug: string;
  /**
   * Tiene que ser la marca del tipo de equipo de abajo. Si la cambias, vuelve a elegir el tipo.
   */
  marca: number | Marca;
  /**
   * Solo aparecen los tipos de la marca elegida arriba.
   */
  tipo: number | TiposEquipo;
  /**
   * Código del modelo, ej. 320D.
   */
  codigo?: string | null;
  descripcion?: string | null;
  imagenes?: (number | Media)[] | null;
  /**
   * Opcional. Debajo ves cómo saldrá en Google y qué se usa si lo dejas vacío.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marcas".
 */
export interface Marca {
  id: number;
  nombre: string;
  /**
   * Es la última parte de la dirección web de esta página. Se crea sola a partir del nombre. Después ya no se puede cambiar, porque Google ya conoce esa dirección. Si tiene una errata, pide a un administrador el permiso «Puede editar slugs ya publicados»: la dirección antigua seguirá llevando a la nueva.
   */
  slug: string;
  descripcion?: string | null;
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipos-equipo".
 */
export interface TiposEquipo {
  id: number;
  nombre: string;
  /**
   * Es la última parte de la dirección web de esta página. Se crea sola a partir del nombre. Después ya no se puede cambiar, porque Google ya conoce esa dirección. Si tiene una errata, pide a un administrador el permiso «Puede editar slugs ya publicados»: la dirección antigua seguirá llevando a la nueva.
   */
  slug: string;
  marca: number | Marca;
  descripcion?: string | null;
  /**
   * Opcional. Debajo ves cómo saldrá en Google y qué se usa si lo dejas vacío.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias-tecnicas".
 */
export interface CategoriasTecnica {
  id: number;
  nombre: string;
  /**
   * Es la última parte de la dirección web de esta página. Se crea sola a partir del nombre. Después ya no se puede cambiar, porque Google ya conoce esa dirección. Si tiene una errata, pide a un administrador el permiso «Puede editar slugs ya publicados»: la dirección antigua seguirá llevando a la nueva.
   */
  slug: string;
  descripcion?: string | null;
  imagen?: (number | null) | Media;
  icono?: ('corte' | 'llanta' | 'lubricante' | 'filtro' | 'motor' | 'rodaje') | null;
  /**
   * Opcional. Vacío: la tarjeta de la portada usa el nombre de la categoría.
   */
  tituloPortada?: string | null;
  /**
   * Ruta del sitio (/…) o https://
   */
  enlace?: string | null;
  /**
   * Vacío: no sale en la portada. 1, 2, 3… es el orden de las tarjetas de «Venta de repuestos».
   */
  ordenPortada?: number | null;
  /**
   * Hoy estas fichas no tienen página propia en el sitio, así que esto no sale en Google. Se guarda para cuando la tengan.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Inventario de maquinaria usada. Se muestra dentro de la página de su categoría; no genera URLs propias.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipos-usados".
 */
export interface EquiposUsado {
  id: number;
  /**
   * Ej. «Excavadora Hitachi ZX200-3».
   */
  nombre: string;
  /**
   * Determina en qué página aparece la unidad.
   */
  categoria: number | CategoriasUsada;
  marca?: string | null;
  modelo?: string | null;
  /**
   * Año del equipo, no de la publicación.
   */
  anio?: number | null;
  /**
   * Horas de trabajo acumuladas. Es el dato que más comparan los compradores.
   */
  horometro?: number | null;
  /**
   * Ciudad donde está el equipo; condiciona el costo de traslado.
   */
  ubicacion?: string | null;
  pesoOperativo?: number | null;
  potencia?: number | null;
  /**
   * Ej. YANMAR 4TNV98CT
   */
  motor?: string | null;
  descripcion?: string | null;
  imagenes?: (number | Media)[] | null;
  /**
   * Al venderse, desmarcar en vez de borrar: conserva el historial y permite deshacer.
   */
  disponible?: boolean | null;
  pestanaPortada?: ('categoria' | 'aditamentos') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias-usada".
 */
export interface CategoriasUsada {
  id: number;
  nombre: string;
  /**
   * Es la última parte de la dirección web de esta página. Se crea sola a partir del nombre. Después ya no se puede cambiar, porque Google ya conoce esa dirección. Si tiene una errata, pide a un administrador el permiso «Puede editar slugs ya publicados»: la dirección antigua seguirá llevando a la nueva.
   */
  slug: string;
  descripcion?: string | null;
  /**
   * Opcional. Debajo ves cómo saldrá en Google y qué se usa si lo dejas vacío.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias-maquinaria".
 */
export interface CategoriasMaquinaria {
  id: number;
  nombre: string;
  /**
   * Es la última parte de la dirección web de esta página. Se crea sola a partir del nombre. Después ya no se puede cambiar, porque Google ya conoce esa dirección. Si tiene una errata, pide a un administrador el permiso «Puede editar slugs ya publicados»: la dirección antigua seguirá llevando a la nueva.
   */
  slug: string;
  descripcion?: string | null;
  /**
   * Tipos de distintas marcas que se listan en esta categoría. Es lo que define su contenido.
   */
  tiposIncluidos?: (number | TiposMaquinaria)[] | null;
  /**
   * Opcional. Debajo ves cómo saldrá en Google y qué se usa si lo dejas vacío.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marcas-lubricante".
 */
export interface MarcasLubricante {
  id: number;
  nombre: string;
  /**
   * Es la última parte de la dirección web de esta página. Se crea sola a partir del nombre. Después ya no se puede cambiar, porque Google ya conoce esa dirección. Si tiene una errata, pide a un administrador el permiso «Puede editar slugs ya publicados»: la dirección antigua seguirá llevando a la nueva.
   */
  slug: string;
  /**
   * Resumen de una o dos líneas, bajo el título.
   */
  entradilla?: string | null;
  descripcion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  logo?: (number | null) | Media;
  /**
   * Opcional. Debajo ves cómo saldrá en Google y qué se usa si lo dejas vacío.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias-lubricante".
 */
export interface CategoriasLubricante {
  id: number;
  nombre: string;
  /**
   * Es la última parte de la dirección web de esta página. Se crea sola a partir del nombre. Después ya no se puede cambiar, porque Google ya conoce esa dirección. Si tiene una errata, pide a un administrador el permiso «Puede editar slugs ya publicados»: la dirección antigua seguirá llevando a la nueva.
   */
  slug: string;
  marca: number | MarcasLubricante;
  /**
   * Resumen de una o dos líneas, bajo el título.
   */
  entradilla?: string | null;
  descripcion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Se usa también como imagen social.
   */
  imagen?: (number | null) | Media;
  /**
   * Nombre comercial y descripción tal como los publica el fabricante. No inventar especificaciones.
   */
  productos?:
    | {
        nombre: string;
        descripcion?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Debajo ves cómo saldrá en Google y qué se usa si lo dejas vacío.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Páginas fijas del sitio (Nosotros, Contacto, textos legales…) y la portada. No cambies la ruta de una página publicada: Google ya conoce esa dirección.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas".
 */
export interface Pagina {
  id: number;
  titulo: string;
  /**
   * La dirección de la página, sin barras al principio ni al final. Ej.: «nosotros» o «nosotros/trabaja-con-nosotros». La portada usa «inicio». Después de crearla ya no se puede cambiar; si tiene una errata, pide a un administrador el permiso «Puede editar slugs ya publicados»: la dirección antigua seguirá llevando a la nueva.
   */
  slug: string;
  /**
   * «Legal / cumplimiento» para tratamiento de datos, términos y similares: tienen que estar siempre en el sitio, así que no se borran.
   */
  tipoPagina?: ('institucional' | 'legal' | 'portada') | null;
  /**
   * Párrafo introductorio bajo el título.
   */
  entradilla?: string | null;
  contenido?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  secciones?:
    | {
        titulo: string;
        /**
         * Identificador del enlace, sin '#'. Debe copiarse EXACTO del sitio actual (distingue mayúsculas): 'taller', 'GARANTIA', 'Devoluciones'.
         */
        ancla: string;
        contenido?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Si añades bloques, la página se compone con ellos y dejan de mostrarse «Contenido» y «Secciones con ancla».
   */
  bloques?:
    | (
        BloqueCabeceraVideo | BloquePresentacionImagen | BloqueCifras | BloqueFranjaMarquee | BloqueTarjetasExpandibles
      )[]
    | null;
  /**
   * Carrusel del inicio. Con una sola diapositiva no se muestran las flechas.
   */
  hero?: {
    diapositivas?:
      | {
          /**
           * Ej. «Potencia Hitachi». Se pinta en mayúsculas por diseño.
           */
          titulo: string;
          /**
           * El texto del recuadro de vidrio. No se muestra en móvil.
           */
          parrafo?: string | null;
          imagenFondo: number | Media;
          /**
           * Opcional. Recorte vertical (p. ej. 1080 × 1620) que se usa por debajo de 768 px. Si se deja vacío, se usa la de escritorio con su punto focal.
           */
          imagenFondoMovil?: (number | null) | Media;
          /**
           * Opcional: va delante del título.
           */
          imagenFrontal?: (number | null) | Media;
          /**
           * Ruta del sitio (/…) o https://
           */
          enlace?: string | null;
          enlaceNombre?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  seccionNueva?: {
    antetitulo?: string | null;
    titulo?: string | null;
    botonTexto?: string | null;
    /**
     * Una ruta del sitio (/…/) o una dirección https://.
     */
    botonEnlace?: string | null;
  };
  seccionUsada?: {
    /**
     * Decorativa: asoma sobre la sección anterior. Opcional.
     */
    imagen?: (number | null) | Media;
    antetitulo?: string | null;
    titulo?: string | null;
    /**
     * Vacío: el nombre de la categoría «excavadoras».
     */
    pestanaExcavadoras?: string | null;
    pestanaOtros?: string | null;
    pestanaAditamentos?: string | null;
    verProductoTexto?: string | null;
    marcasTitulo?: string | null;
    marcasTexto?: string | null;
    /**
     * El botón lleva a la categoría «excavadoras» de usados.
     */
    botonTexto?: string | null;
  };
  seccionLogos?: {
    /**
     * En este orden en el carrusel. PNG transparente, con el logo centrado en su lienzo.
     */
    logos?:
      | {
          logo: number | Media;
          /**
           * Es el texto alternativo del logo.
           */
          nombre: string;
          id?: string | null;
        }[]
      | null;
  };
  seccionRepuestos?: {
    antetitulo?: string | null;
    titulo?: string | null;
    verMasTexto?: string | null;
    botonTexto?: string | null;
    /**
     * Una ruta del sitio (/…/) o una dirección https://.
     */
    botonEnlace?: string | null;
  };
  seccionCompania?: {
    /**
     * En bucle y sin sonido. MP4 H.264 de 8 bits, máximo 4 MB.
     */
    video?: (number | null) | Video;
    /**
     * Opcional. Se abre en una ventana, desde youtube-nocookie.com, solo al pulsar.
     */
    youtube?: string | null;
    titulo?: string | null;
    texto?: string | null;
    marquesina?: string | null;
    /**
     * Una ruta del sitio (/…/) o una dirección https://.
     */
    marquesinaEnlace?: string | null;
  };
  seccionCatalogo?: {
    titulo?: string | null;
    catalogoTexto?: string | null;
    /**
     * Una ruta del sitio (/…/) o una dirección https://.
     */
    catalogoEnlace?: string | null;
    /**
     * El número sale de la configuración de la empresa.
     */
    whatsappTexto?: string | null;
  };
  seccionSedes?: {
    /**
     * ux-9 no pinta título en esta sección; este lo leen los lectores de pantalla.
     */
    titulo?: string | null;
  };
  seccionTestimonios?: {
    titulo?: string | null;
    verVideoTexto?: string | null;
  };
  seccionFaq?: {
    /**
     * Decorativa: asoma arriba a la izquierda. Opcional.
     */
    imagen?: (number | null) | Media;
    titulo?: string | null;
    intro?: string | null;
    botonTexto?: string | null;
    /**
     * Una ruta del sitio (/…/) o una dirección https://.
     */
    botonEnlace?: string | null;
  };
  /**
   * Opcional. Debajo ves cómo saldrá en Google y qué se usa si lo dejas vacío.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueCabeceraVideo".
 */
export interface BloqueCabeceraVideo {
  /**
   * Texto corto encima del título. Opcional.
   */
  antetitulo?: string | null;
  /**
   * Es el título principal de la página (su <h1>). Úsalo una sola vez por página.
   */
  titulo: string;
  /**
   * En bucle y sin sonido; su póster se ve mientras carga y con «reducir movimiento». Opcional.
   */
  video?: (number | null) | Video;
  /**
   * Se usa si no hay vídeo. Con vídeo, manda el póster del vídeo.
   */
  imagen?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cabeceraVideo';
}
/**
 * Vídeos del sitio: MP4 o WebM, máximo 4 MB, con imagen de póster obligatoria.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  /**
   * Para quien no lo ve. Aunque sea decorativo, dilo aquí: es lo que queda en el panel.
   */
  descripcion: string;
  /**
   * Lo que se ve antes de cargar, con «reducir movimiento» activado, al pausar y si el vídeo no se puede reproducir.
   */
  poster: number | Media;
  /**
   * Un vídeo de fondo sin información se oculta a los lectores de pantalla.
   */
  decorativo?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloquePresentacionImagen".
 */
export interface BloquePresentacionImagen {
  /**
   * A un lado del texto (debajo en móvil). Si transmite información, como un mapa, cuida su texto alternativo.
   */
  imagen?: (number | null) | Media;
  /**
   * Se reproduce una vez, en el sitio de la imagen, al llegar con el scroll. La imagen sigue haciendo falta: es lo que se ve con «reducir movimiento», si la animación no carga y lo que lee un lector de pantalla. Usa como imagen el último fotograma.
   */
  lottie?: (number | null) | Animacion;
  /**
   * Texto corto encima del título. Opcional.
   */
  antetitulo?: string | null;
  titulo: string;
  texto?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  botonTexto?: string | null;
  /**
   * Una ruta del sitio (/…/) o una dirección https://. Vacío: sin botón.
   */
  botonEnlace?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'presentacionImagen';
}
/**
 * Animaciones Lottie (.json exportado con Bodymovin, sin expresiones), máximo 4 MB. Se reproducen una vez al llegar con el scroll.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "animaciones".
 */
export interface Animacion {
  id: number;
  /**
   * Para el panel. Lo que lee un lector de pantalla es el texto alternativo de la imagen fija del bloque.
   */
  descripcion: string;
  /**
   * Lo lee del fichero al subirlo.
   */
  ancho?: number | null;
  alto?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueCifras".
 */
export interface BloqueCifras {
  /**
   * El número cuenta desde cero al llegar con el scroll.
   */
  cifras?:
    | {
        /**
         * Ej. «+».
         */
        prefijo?: string | null;
        /**
         * Sin separadores: 10000.
         */
        numero: number;
        /**
         * Ej. «%» o «+».
         */
        sufijo?: string | null;
        etiqueta: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cifras';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueFranjaMarquee".
 */
export interface BloqueFranjaMarquee {
  /**
   * Se repite de lado a lado, en mayúsculas. Ej. «Marcas aliadas».
   */
  texto: string;
  /**
   * Decorativa.
   */
  imagenFondo?: (number | null) | Media;
  /**
   * Va delante del texto. Decorativa. Opcional.
   */
  imagenFrontal?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'franjaMarquee';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueTarjetasExpandibles".
 */
export interface BloqueTarjetasExpandibles {
  /**
   * Texto corto encima del título. Opcional.
   */
  antetitulo?: string | null;
  titulo: string;
  /**
   * Una abierta y las demás plegadas; rotan cada 4 s. Con más de 4 las plegadas quedan muy estrechas.
   */
  tarjetas?:
    | {
        titulo: string;
        /**
         * Se ve con la tarjeta abierta.
         */
        texto?: string | null;
        imagen?: (number | null) | Media;
        /**
         * Una ruta del sitio (/…/) o una dirección https://. Opcional.
         */
        enlace?: string | null;
        id?: string | null;
      }[]
    | null;
  botonTexto?: string | null;
  /**
   * Una ruta del sitio (/…/) o una dirección https://. Vacío: sin botón.
   */
  botonEnlace?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tarjetasExpandibles';
}
/**
 * Cada artículo vive en partequipos.com/<slug>/. Su slug no puede repetir el de una página.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articulos".
 */
export interface Articulo {
  id: number;
  titulo: string;
  /**
   * Es la última parte de la dirección web de esta página. Se crea sola a partir del nombre. Después ya no se puede cambiar, porque Google ya conoce esa dirección. Si tiene una errata, pide a un administrador el permiso «Puede editar slugs ya publicados»: la dirección antigua seguirá llevando a la nueva.
   */
  slug: string;
  /**
   * En qué listado del blog aparece el artículo.
   */
  categoria?: (number | null) | CategoriasBlog;
  /**
   * Ordena el blog (lo más reciente primero) y es la fecha que ven los buscadores.
   */
  fechaPublicacion: string;
  /**
   * Firma que aparece en el artículo. Vacío: «Partequipos». Con un nombre de persona, los buscadores lo leen como autor (persona); con «Partequipos», como la empresa.
   */
  autor?: string | null;
  /**
   * Resumen para el índice y para la descripción social.
   */
  entradilla?: string | null;
  /**
   * Se usa en el índice y como imagen social.
   */
  imagenDestacada?: (number | null) | Media;
  contenido?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Opcional. Debajo ves cómo saldrá en Google y qué se usa si lo dejas vacío.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias-blog".
 */
export interface CategoriasBlog {
  id: number;
  nombre: string;
  /**
   * Es la última parte de la dirección web de esta página. Se crea sola a partir del nombre. Después ya no se puede cambiar, porque Google ya conoce esa dirección. Si tiene una errata, pide a un administrador el permiso «Puede editar slugs ya publicados»: la dirección antigua seguirá llevando a la nueva.
   */
  slug: string;
  descripcion?: string | null;
  /**
   * Opcional. Debajo ves cómo saldrá en Google y qué se usa si lo dejas vacío.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preguntas-frecuentes".
 */
export interface PreguntasFrecuente {
  id: number;
  pregunta: string;
  respuesta: string;
  orden?: number | null;
  publicada?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Testimonios de la portada. Un testimonio no se publica sin la autorización de uso de la persona.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonios".
 */
export interface Testimonio {
  id: number;
  nombre: string;
  empresa?: string | null;
  ciudad?: string | null;
  cita: string;
  foto?: (number | null) | Media;
  /**
   * Opcional. Un MP4 propio; para YouTube, el campo de abajo.
   */
  video?: (number | null) | Video;
  /**
   * Opcional. Enlace de YouTube; si lleva «&t=21s», empieza en ese segundo.
   */
  youtube?: string | null;
  autorizacionUso?: boolean | null;
  fechaAutorizacion?: string | null;
  /**
   * Para poder encontrarlo si la persona pide retirar su testimonio.
   */
  referenciaAutorizacion?: string | null;
  /**
   * Solo se puede marcar con la autorización de uso marcada.
   */
  publicado?: boolean | null;
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sedes del mapa de la portada. No generan URLs propias.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sedes".
 */
export interface Sede {
  id: number;
  /**
   * Nombre de la sede. La ficha dice «Sede <nombre>». Ej. «Bogotá», «Antioquia».
   */
  nombre: string;
  /**
   * Ej. «Medellín» en la sede Antioquia.
   */
  ciudad: string;
  /**
   * Ej. «Antioquia». Etiqueta: «Ciudad, Departamento».
   */
  departamento: string;
  latitud: number;
  longitud: number;
  /**
   * Cada línea con su dirección. Ej. Maquinaria · Diagonal 16 # 96 G – 85.
   */
  lineas?:
    | {
        linea: string;
        /**
         * Solo si no es el de la sede. Ej. «Guarne» en Antioquia.
         */
        localidad?: string | null;
        direccion: string;
        /**
         * Opcional: en ux-9, tres sedes no tienen teléfono. Con indicativo. Ej. (601) 492 62 60.
         */
        telefono?: string | null;
        id?: string | null;
      }[]
    | null;
  foto?: (number | null) | Media;
  /**
   * Menor primero.
   */
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Redirecciones de URLs antiguas hacia las vigentes. Evita perder posicionamiento cuando una URL cambia.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Ruta antigua, empezando por «/». Ej: /repuestos-viejo/modelo-x
   */
  desde: string;
  /**
   * Ruta vigente o URL absoluta a la que se redirige.
   */
  hacia: string;
  /**
   * 301 salvo que la redirección sea realmente temporal.
   */
  tipo: '301' | '302';
  /**
   * Cómo se creó esta redirección. Las automáticas no deben editarse a la ligera.
   */
  origen: 'manual' | 'cambio-de-slug' | 'migracion';
  notas?: string | null;
  /**
   * Lo actualiza el equipo técnico al revisar las redirecciones. «Sin contenido» es normal mientras se migra; «No corresponde a ninguna ruta» hay que corregirlo antes de publicar.
   */
  estadoDestino?: ('sin-verificar' | 'resuelve' | 'sin-contenido' | 'sin-ruta' | 'externa') | null;
  destinoVerificadoEn?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cuentas con acceso al panel. Solo un administrador puede crear usuarios o cambiar roles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * El editor no puede crear usuarios, cambiar roles ni borrar registros. Solo un administrador cambia este campo.
   */
  rol: 'administrador' | 'editor';
  /**
   * Permite cambiar el slug de lo que ya está publicado. Úsalo solo para corregir erratas: la dirección antigua seguirá llevando a la nueva, pero Google tarda en enterarse.
   */
  puedeEditarSlugs?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'solicitudes';
        value: number | Solicitude;
      } | null)
    | ({
        relationTo: 'modelos-repuesto';
        value: number | ModelosRepuesto;
      } | null)
    | ({
        relationTo: 'marcas';
        value: number | Marca;
      } | null)
    | ({
        relationTo: 'tipos-equipo';
        value: number | TiposEquipo;
      } | null)
    | ({
        relationTo: 'categorias-tecnicas';
        value: number | CategoriasTecnica;
      } | null)
    | ({
        relationTo: 'equipos-nuevos';
        value: number | EquiposNuevo;
      } | null)
    | ({
        relationTo: 'equipos-usados';
        value: number | EquiposUsado;
      } | null)
    | ({
        relationTo: 'marcas-maquinaria';
        value: number | MarcasMaquinaria;
      } | null)
    | ({
        relationTo: 'tipos-maquinaria';
        value: number | TiposMaquinaria;
      } | null)
    | ({
        relationTo: 'categorias-maquinaria';
        value: number | CategoriasMaquinaria;
      } | null)
    | ({
        relationTo: 'categorias-usada';
        value: number | CategoriasUsada;
      } | null)
    | ({
        relationTo: 'marcas-lubricante';
        value: number | MarcasLubricante;
      } | null)
    | ({
        relationTo: 'categorias-lubricante';
        value: number | CategoriasLubricante;
      } | null)
    | ({
        relationTo: 'paginas';
        value: number | Pagina;
      } | null)
    | ({
        relationTo: 'articulos';
        value: number | Articulo;
      } | null)
    | ({
        relationTo: 'categorias-blog';
        value: number | CategoriasBlog;
      } | null)
    | ({
        relationTo: 'preguntas-frecuentes';
        value: number | PreguntasFrecuente;
      } | null)
    | ({
        relationTo: 'testimonios';
        value: number | Testimonio;
      } | null)
    | ({
        relationTo: 'sedes';
        value: number | Sede;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documentos';
        value: number | Documento;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'animaciones';
        value: number | Animacion;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solicitudes_select".
 */
export interface SolicitudesSelect<T extends boolean = true> {
  tipo?: T;
  estado?: T;
  nombre?: T;
  correo?: T;
  telefono?: T;
  empresa?: T;
  mensaje?: T;
  referencia?: T;
  referenciaTexto?: T;
  origen?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modelos-repuesto_select".
 */
export interface ModelosRepuestoSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  marca?: T;
  tipo?: T;
  codigo?: T;
  descripcion?: T;
  imagenes?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marcas_select".
 */
export interface MarcasSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  descripcion?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipos-equipo_select".
 */
export interface TiposEquipoSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  marca?: T;
  descripcion?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias-tecnicas_select".
 */
export interface CategoriasTecnicasSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  descripcion?: T;
  imagen?: T;
  icono?: T;
  tituloPortada?: T;
  enlace?: T;
  ordenPortada?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipos-nuevos_select".
 */
export interface EquiposNuevosSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  marca?: T;
  tipo?: T;
  codigo?: T;
  entradilla?: T;
  descripcion?: T;
  destacados?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  imagenes?: T;
  fichaTecnica?:
    | T
    | {
        etiqueta?: T;
        valor?: T;
        destacar?: T;
        icono?: T;
        id?: T;
      };
  fichaTecnicaPdf?: T;
  documentos?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipos-usados_select".
 */
export interface EquiposUsadosSelect<T extends boolean = true> {
  nombre?: T;
  categoria?: T;
  marca?: T;
  modelo?: T;
  anio?: T;
  horometro?: T;
  ubicacion?: T;
  pesoOperativo?: T;
  potencia?: T;
  motor?: T;
  descripcion?: T;
  imagenes?: T;
  disponible?: T;
  pestanaPortada?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marcas-maquinaria_select".
 */
export interface MarcasMaquinariaSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  descripcion?: T;
  logo?: T;
  imagenTarjeta?: T;
  ordenPortada?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipos-maquinaria_select".
 */
export interface TiposMaquinariaSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  marca?: T;
  descripcion?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias-maquinaria_select".
 */
export interface CategoriasMaquinariaSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  descripcion?: T;
  tiposIncluidos?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias-usada_select".
 */
export interface CategoriasUsadaSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  descripcion?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marcas-lubricante_select".
 */
export interface MarcasLubricanteSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  entradilla?: T;
  descripcion?: T;
  logo?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias-lubricante_select".
 */
export interface CategoriasLubricanteSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  marca?: T;
  entradilla?: T;
  descripcion?: T;
  imagen?: T;
  productos?:
    | T
    | {
        nombre?: T;
        descripcion?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas_select".
 */
export interface PaginasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  tipoPagina?: T;
  entradilla?: T;
  contenido?: T;
  secciones?:
    | T
    | {
        titulo?: T;
        ancla?: T;
        contenido?: T;
        id?: T;
      };
  bloques?:
    | T
    | {
        cabeceraVideo?: T | BloqueCabeceraVideoSelect<T>;
        presentacionImagen?: T | BloquePresentacionImagenSelect<T>;
        cifras?: T | BloqueCifrasSelect<T>;
        franjaMarquee?: T | BloqueFranjaMarqueeSelect<T>;
        tarjetasExpandibles?: T | BloqueTarjetasExpandiblesSelect<T>;
      };
  hero?:
    | T
    | {
        diapositivas?:
          | T
          | {
              titulo?: T;
              parrafo?: T;
              imagenFondo?: T;
              imagenFondoMovil?: T;
              imagenFrontal?: T;
              enlace?: T;
              enlaceNombre?: T;
              id?: T;
            };
      };
  seccionNueva?:
    | T
    | {
        antetitulo?: T;
        titulo?: T;
        botonTexto?: T;
        botonEnlace?: T;
      };
  seccionUsada?:
    | T
    | {
        imagen?: T;
        antetitulo?: T;
        titulo?: T;
        pestanaExcavadoras?: T;
        pestanaOtros?: T;
        pestanaAditamentos?: T;
        verProductoTexto?: T;
        marcasTitulo?: T;
        marcasTexto?: T;
        botonTexto?: T;
      };
  seccionLogos?:
    | T
    | {
        logos?:
          | T
          | {
              logo?: T;
              nombre?: T;
              id?: T;
            };
      };
  seccionRepuestos?:
    | T
    | {
        antetitulo?: T;
        titulo?: T;
        verMasTexto?: T;
        botonTexto?: T;
        botonEnlace?: T;
      };
  seccionCompania?:
    | T
    | {
        video?: T;
        youtube?: T;
        titulo?: T;
        texto?: T;
        marquesina?: T;
        marquesinaEnlace?: T;
      };
  seccionCatalogo?:
    | T
    | {
        titulo?: T;
        catalogoTexto?: T;
        catalogoEnlace?: T;
        whatsappTexto?: T;
      };
  seccionSedes?:
    | T
    | {
        titulo?: T;
      };
  seccionTestimonios?:
    | T
    | {
        titulo?: T;
        verVideoTexto?: T;
      };
  seccionFaq?:
    | T
    | {
        imagen?: T;
        titulo?: T;
        intro?: T;
        botonTexto?: T;
        botonEnlace?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueCabeceraVideo_select".
 */
export interface BloqueCabeceraVideoSelect<T extends boolean = true> {
  antetitulo?: T;
  titulo?: T;
  video?: T;
  imagen?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloquePresentacionImagen_select".
 */
export interface BloquePresentacionImagenSelect<T extends boolean = true> {
  imagen?: T;
  lottie?: T;
  antetitulo?: T;
  titulo?: T;
  texto?: T;
  botonTexto?: T;
  botonEnlace?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueCifras_select".
 */
export interface BloqueCifrasSelect<T extends boolean = true> {
  cifras?:
    | T
    | {
        prefijo?: T;
        numero?: T;
        sufijo?: T;
        etiqueta?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueFranjaMarquee_select".
 */
export interface BloqueFranjaMarqueeSelect<T extends boolean = true> {
  texto?: T;
  imagenFondo?: T;
  imagenFrontal?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueTarjetasExpandibles_select".
 */
export interface BloqueTarjetasExpandiblesSelect<T extends boolean = true> {
  antetitulo?: T;
  titulo?: T;
  tarjetas?:
    | T
    | {
        titulo?: T;
        texto?: T;
        imagen?: T;
        enlace?: T;
        id?: T;
      };
  botonTexto?: T;
  botonEnlace?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articulos_select".
 */
export interface ArticulosSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  categoria?: T;
  fechaPublicacion?: T;
  autor?: T;
  entradilla?: T;
  imagenDestacada?: T;
  contenido?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias-blog_select".
 */
export interface CategoriasBlogSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  descripcion?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preguntas-frecuentes_select".
 */
export interface PreguntasFrecuentesSelect<T extends boolean = true> {
  pregunta?: T;
  respuesta?: T;
  orden?: T;
  publicada?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonios_select".
 */
export interface TestimoniosSelect<T extends boolean = true> {
  nombre?: T;
  empresa?: T;
  ciudad?: T;
  cita?: T;
  foto?: T;
  video?: T;
  youtube?: T;
  autorizacionUso?: T;
  fechaAutorizacion?: T;
  referenciaAutorizacion?: T;
  publicado?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sedes_select".
 */
export interface SedesSelect<T extends boolean = true> {
  nombre?: T;
  ciudad?: T;
  departamento?: T;
  latitud?: T;
  longitud?: T;
  lineas?:
    | T
    | {
        linea?: T;
        localidad?: T;
        direccion?: T;
        telefono?: T;
        id?: T;
      };
  foto?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos_select".
 */
export interface DocumentosSelect<T extends boolean = true> {
  titulo?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  descripcion?: T;
  poster?: T;
  decorativo?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "animaciones_select".
 */
export interface AnimacionesSelect<T extends boolean = true> {
  descripcion?: T;
  ancho?: T;
  alto?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  desde?: T;
  hacia?: T;
  tipo?: T;
  origen?: T;
  notas?: T;
  estadoDestino?: T;
  destinoVerificadoEn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  rol?: T;
  puedeEditarSlugs?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Menú y botón de la cabecera de todas las páginas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cabecera".
 */
export interface Cabecera {
  id: number;
  enlaces?:
    | {
        etiqueta: string;
        /**
         * Una ruta del sitio (/…/) o https://.
         */
        enlace: string;
        id?: string | null;
      }[]
    | null;
  botonTexto?: string | null;
  botonEnlace?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Texto y enlaces del pie de todas las páginas. Las redes y el contacto se editan en la configuración de la empresa, no aquí.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pie".
 */
export interface Pie {
  id: number;
  lema: string;
  /**
   * El número sale de la configuración de la empresa.
   */
  textoBoton: string;
  /**
   * Opcional. Máquina recortada (PNG transparente) que asoma sobre la esquina derecha de la tarjeta roja, solo en escritorio. Vacío: la tarjeta sin imagen.
   */
  imagenDecorativa?: (number | null) | Media;
  empresaTitulo?: string | null;
  empresaTexto?: string | null;
  columnas?:
    | {
        titulo: string;
        enlaces?:
          | {
              etiqueta: string;
              tipo: 'pagina' | 'telefono';
              /**
               * Ruta del sitio (/…) o https://
               */
              destino?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  legales?:
    | {
        etiqueta: string;
        enlace: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Datos de la empresa que usan los buscadores y el sitio: el horario de atención, el logo y el contacto.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number;
  /**
   * Un tramo por grupo de días con el mismo horario. Ejemplo: lunes a viernes de 08:00 a 17:30.
   */
  horario?:
    | {
        dias: ('Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday')[];
        abre: string;
        cierra: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Sale en la cabecera, el pie y la información que leen los buscadores (y al compartir en redes, si no hay imagen al compartir por defecto). Usa un PNG con fondo transparente y letras oscuras, de al menos 520 px de ancho. Si lo dejas vacío, se usa el logo de siempre.
   */
  logo?: (number | null) | Media;
  /**
   * La que sale al compartir en redes (WhatsApp, Facebook, LinkedIn…) las páginas que no tienen imagen propia. Usa una imagen opaca, sin transparencia, de 1200 × 630 px. Si la dejas vacía, se usa el logo.
   */
  imagenSocial?: (number | null) | Media;
  /**
   * La que sale a la izquierda de la pantalla para entrar al panel, solo en computador. Mejor una imagen cuadrada o vertical y oscura, porque lleva texto blanco encima. Si la dejas vacía, sale un fondo rojo degradado.
   */
  imagenAcceso?: (number | null) | Media;
  /**
   * Sale en el pie, la cabecera, el botón de WhatsApp y la información que leen los buscadores. Si dejas un campo vacío, se usa el dato de siempre.
   */
  empresa?: {
    telefono?: string | null;
    /**
     * Si lo dejas vacío, se usa el teléfono.
     */
    whatsapp?: string | null;
    correo?: string | null;
    direccion?: string | null;
    ciudad?: string | null;
    /**
     * La dirección completa de cada perfil oficial. En el pie salen LinkedIn, X, Facebook, Instagram, TikTok y YouTube, en el orden en que estén aquí; las demás solo las leen los buscadores.
     */
    redes?:
      | {
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Lo que comparten todas las fichas de maquinaria nueva.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ficha-producto".
 */
export interface FichaProducto {
  id: number;
  /**
   * Opcional. Persona o máquina recortada (PNG transparente) a la derecha del recuadro de contacto, al final de cada ficha. Vacío: el recuadro sin imagen.
   */
  imagenContacto?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cabecera_select".
 */
export interface CabeceraSelect<T extends boolean = true> {
  enlaces?:
    | T
    | {
        etiqueta?: T;
        enlace?: T;
        id?: T;
      };
  botonTexto?: T;
  botonEnlace?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pie_select".
 */
export interface PieSelect<T extends boolean = true> {
  lema?: T;
  textoBoton?: T;
  imagenDecorativa?: T;
  empresaTitulo?: T;
  empresaTexto?: T;
  columnas?:
    | T
    | {
        titulo?: T;
        enlaces?:
          | T
          | {
              etiqueta?: T;
              tipo?: T;
              destino?: T;
              id?: T;
            };
        id?: T;
      };
  legales?:
    | T
    | {
        etiqueta?: T;
        enlace?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  horario?:
    | T
    | {
        dias?: T;
        abre?: T;
        cierra?: T;
        id?: T;
      };
  logo?: T;
  imagenSocial?: T;
  imagenAcceso?: T;
  empresa?:
    | T
    | {
        telefono?: T;
        whatsapp?: T;
        correo?: T;
        direccion?: T;
        ciudad?: T;
        redes?:
          | T
          | {
              url?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ficha-producto_select".
 */
export interface FichaProductoSelect<T extends boolean = true> {
  imagenContacto?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}